/** Ash copy banks. Voice: sharp, funny, specific. Roast behavior, not bodies. */

export const who = {
  idle: [
    "Ash · Head of Honesty",
    "Ash · Waiting",
    "Ash · Clock's running",
    "Ash · Unpaid referee",
  ],
  roast: [
    "Ash · Head of Honesty",
    "Ash · Physics department",
    "Ash · Unpaid referee",
    "Ash · Not your hype man",
    "Ash · The snag in the story",
  ],
  hype: [
    "Ash · Head of Honesty",
    "Ash · Quiet applause",
    "Ash · Fire noticed",
    "Ash · Keep it boring",
    "Ash · Rare accuracy",
  ],
  mixed: [
    "Ash · Head of Honesty",
    "Ash · Undecided weather",
    "Ash · Beige alert",
    "Ash · Pick a lane",
  ],
};

export const greet = [
  "Don't tell me your plans. Show me the plate.",
  "Heat doesn't care about your mood. It cares about the log.",
  "Another day. Same physics. Try not to negotiate.",
  "If you're here to be soothed, wrong app. If you're here to climb, feed it.",
  "The fire is on. You're still in the lobby.",
  "We can do the speech later. Log breakfast like an adult.",
  "Motivation is a tourist. Habit lives here. Start the meter.",
  "You opened the app. That's 8%. The other 92% is chewing and iron.",
  "I don't do horoscopes. I do grams.",
  "Silence on the plate is still a choice. A cowardly one.",
  "The day already started without your permission. Catch up.",
  "Coffee is not a meal. Charming try though.",
  "If this is a 'quick check,' make it a real log or close me.",
  "Yesterday's Heat does not babysit today. Prove it again.",
  "You look like someone about to make a deal with a croissant. Don't.",
  "Rank is a receipt. You haven't bought anything yet.",
  "I'm not hungry. You might be. That's the whole plot.",
  "Open Fuel. Pick a slot. Stop narrating your intentions.",
  "The weights are patient. Ash is not. Move.",
  "A blank log is a novel with no verbs. Write one.",
  "You didn't come here to admire the fire. Feed it or freeze.",
  "Streaks die in the morning. That's not poetry. That's statistics.",
  "Your future self is not logging this for you. Unromantic, I know.",
  "We can roast after you've eaten something with a name.",
  "The meter is a mirror. Right now it's a black screen. Tap something.",
  "Discipline is boring on purpose. Be boring before noon.",
  "If you needed a pep talk, you wanted a different mascot.",
  "Heat is earned in public with private chewing. Get chewing.",
  "I'm still here. The protein isn't. Priorities.",
  "Today's physics are not on sale. Full price. Log it.",
  "You can scroll later. The plate is the plot.",
  "A plan in your head has zero kcal. Convenient. Useless.",
  "The fire doesn't do RSVPs. Show up with food and a session.",
  "Good morning is a greeting. A log is a relationship.",
  "If you're waiting to 'feel ready,' that's a hobby, not a cut.",
  "The app is free. Your excuses are expensive. Pick.",
  "I kept the lights on. You keep the honesty on.",
  "Start ugly. Perfect mornings are how weeks vanish.",
  "You don't need a montage. You need oats or eggs. Pick one.",
  "The day will happen either way. Make the log less fictional.",
];

export const empty = [
  "You logged nothing. That's not a deficit. That's a disappearing act.",
  "Air is not a macronutrient. Try again when you're ready to be a person.",
  "The fire went looking for you. It found a couch and a notification.",
  "Zero kcal isn't monk mode. It's a blank page with swagger.",
  "You can't close a day you never opened. That's theater.",
  "Invisible eating is still eating. Invisible logging is lying.",
  "The plate filed for abandonment. I notarized it.",
  "A fast without a log is just a secret. Secrets don't raise Heat.",
  "You treated the day like a draft. Heat publishes finals only.",
  "Nothing logged, plenty implied. I don't score implications.",
  "If the goal was stealth, congratulations. The fire is unimpressed.",
  "Empty logs don't make you mysterious. They make you unmeasurable.",
  "You ghosted your own nutrition. Bold. Also stupid.",
  "I can't roast a meal that doesn't exist. That's your only mercy today.",
  "This is how people 'forget' 800 kcal and call it intuition.",
  "The diary is blank. The body is not a diary. Log anyway.",
  "You brought attendance and no offering. Temples hate that.",
  "Zero is a number. It's also a confession.",
  "We don't do spiritual deficits. We do grams. You did neither.",
  "The fire doesn't chase. You either show up or cool off.",
  "A closed day with no food is a magic trick. I don't clap for those.",
  "You outsourced honesty to tomorrow. Tomorrow already has a job.",
  "Blank isn't aesthetic. Blank is unpaid labor for future-you.",
  "If you ate, log it. If you didn't, that's the plot. Either way: type.",
  "I waited. You wandered. Heat left a note: 'try again with food.'",
];

export const over = [
  "You didn't 'listen to your body.' Your body asked for a parade and you funded it.",
  "That wasn't a refeed. That was a hostage situation with a menu.",
  "Calories aren't feelings. You ate the feeling anyway.",
  "Bold of you to call this a cut while eating like a harvest festival.",
  "The buffer called. It's in a witness protection program.",
  "You didn't overshoot. You paved a runway.",
  "That's not fuel. That's a festival with better lighting.",
  "Heat can count. You were hoping it couldn't.",
  "You treated the target like a suggestion box. It isn't.",
  "Portion control left the chat and started a podcast without you.",
  "If this was 'one bite,' the bite had a postcode.",
  "You didn't cheat. Cheating implies a plan. This was weather.",
  "The surplus isn't a vibe. It's arithmetic wearing your leftovers.",
  "You stacked meals like they were apologies. They weren't.",
  "I saw the log. The log saw the sun. Neither of us blinked.",
  "That extra wasn't 'for energy.' Energy doesn't need a second dessert.",
  "You negotiated with the meter. The meter doesn't speak human.",
  "A little over is human. This was a committee decision.",
  "You ate past full and called it culture. Culture still has kcal.",
  "The target wasn't hiding. You walked around it on purpose.",
  "If hunger was the villain, you hired it as a consultant.",
  "You didn't lose control. You lent it out and forgot to collect.",
  "That's a generous interpretation of 'maintenance.' Generous to the plate.",
  "You can call it a celebration. Physics will call it Tuesday's math.",
  "The fire doesn't shame hunger. It shames the fiction around it.",
  "You packed the day like a suitcase for a two-week trip.",
  "Overshooting once is data. This looks like a hobby.",
  "You weren't 'off plan.' You were on a different plan with worse lighting.",
  "If the goal was fullness, you won. If the goal was the target, see me after class.",
  "You added 'just in case' calories. In case of what, winter?",
  "The log is honest. Your story about the log is fan fiction.",
  "You treated protein like a side quest and dessert like the campaign.",
  "That's not intuitive eating. That's improvisational accounting.",
  "You went looking for satisfaction in a place that sells seconds.",
  "A surplus this loud doesn't need a caption. It needs a nap and a reset.",
  "You didn't listen to fullness cues. You put them on mute and danced.",
  "The meter isn't dramatic. You are. The numbers are calm.",
  "You ate like the target was a rumor. It was printed on the screen.",
  "If this is stress, log the stress. Don't launder it through snacks.",
  "You can still finish the day like an adult. Start by admitting the total.",
];

export const under = [
  "Starving yourself isn't discipline. It's a tantrum with better branding.",
  "You can't out-suffer a protein target you never met.",
  "Undereating isn't a personality. It's how people bounce back harder tomorrow.",
  "A tiny log isn't a flex. It's a sequel waiting to overeat.",
  "You didn't earn extra Heat by disappearing meals. You earned a rebound.",
  "Low isn't lean if it's a panic. Eat like you have a tomorrow.",
  "Discipline eats. Martyrdom screenshots empty plates.",
  "The fire wants honesty, not a hunger strike with branding.",
  "You're not 'locked in.' You're running on fumes and narrative.",
  "Targets exist so you don't have to guess how little is too little.",
  "You left calories on the table and called it virtue. It isn't.",
  "Heat doesn't applaud suffering. It applauds hitting the number.",
  "This is how people 'be good' until 9pm. Don't be those people.",
  "A deficit is a plan. This looks like you forgot you have a body.",
  "Eat the food. Then we can talk about willpower like grown-ups.",
  "You can't build a cut on skipped lunch and moral superiority.",
  "The goal wasn't to vanish. It was to land near the target.",
  "Underfeeding the day is how nights get loud. You've met nights.",
  "Protein can't teleport. Put it on a fork.",
  "You're not impressing the fire. You're confusing it.",
  "Low energy isn't a badge. It's a warning light you decorated.",
  "If you're dizzy and proud, we have different definitions of winning.",
  "The target has a floor. You brought a trapdoor.",
  "Save the fasting lore for people who don't lift. You do. Eat.",
  "A quiet stomach isn't always a win. Sometimes it's a postponement.",
  "You can be in a deficit without turning into a rumor.",
  "This isn't control. Control would still include dinner.",
  "The math works better when there's math to do. Add food.",
  "You don't get extra credit for being difficult to feed.",
  "Eat. Log. Then be smug. Order of operations.",
  "A ghosted lunch doesn't make dinner holier. It makes dinner feral.",
  "You're playing life on hard mode with the tutorial skipped.",
  "The plate isn't the enemy. The blank hours are.",
  "Come back with a meal that has a last name.",
  "I don't score potential. I score lunch. Bring lunch.",
];

export const skip = [
  "Rest days are programmed. This was just you losing a negotiation with your shoes.",
  "The weights didn't miss you. They just noticed you were optional.",
  "You had time. You had a phone. You had excuses ranked by originality.",
  "Movement isn't a personality quiz. It's a yes or a no. You picked no.",
  "The session didn't cancel you. You RSVP'd with a shrug.",
  "You can eat perfectly and still be a tourist in your own program.",
  "Iron is patient. Your joints are taking notes on the absence.",
  "A rest day has a plan. This had a sofa and a plot twist.",
  "You trained your thumb. The barbell filed a complaint.",
  "Skipping once is life. Skipping with a speech is a brand.",
  "The fire asked for a pulse check. You sent a meme.",
  "You don't need a two-hour epic. You needed twenty honest minutes.",
  "Conditioning isn't a rumor. Show up messy. Show up.",
  "The walk counted if it happened. It didn't. That's the review.",
  "You saved the workout for a better version of you. They didn't clock in.",
  "Rest is recovery. This is hide-and-seek with your standards.",
  "Your program isn't allergic to short sessions. You are.",
  "The gym didn't ghost you. Check your sent folder.",
  "You can log food like a saint and still owe the iron rent.",
  "A 'busy day' still has hallways. Hallways have walking.",
  "You negotiated with tomorrow again. Tomorrow is tired of you.",
  "Sweat is optional. Honesty about not sweating isn't.",
  "The lift doesn't need your mood. It needs your presence.",
  "You stretched the definition of rest until it meant nothing.",
  "If the goal includes muscle, the couch is a competing offer.",
  "You didn't deload. You just didn't load.",
  "Ten minutes exists. You spent it explaining why ten minutes doesn't.",
  "The session was short. Your avoidance was novel-length.",
  "Shoes work better on feet than in the hallway as décor.",
  "You can be sore tomorrow or sorry tonight. Pick the useful one.",
  "Training is the plot twist your calories are waiting for.",
  "I believe you were tired. I also believe you had twenty minutes.",
  "The barbell doesn't do feelings. It does attendance.",
  "You left Heat a voicemail. Heat doesn't check voicemail.",
  "Move something that isn't your thumbs. That's the note.",
];

export const protein = [
  "You ate like a hummingbird and expected to rebuild like a blacksmith.",
  "Protein isn't a vibe. It's grams. You brought vibes.",
  "Your muscles filed a missing person report. I signed it.",
  "That was a carbohydrate story with a protein cameo.",
  "You can't garnish your way to the protein target.",
  "The target wasn't hiding in the sauce. It was in the meat, dairy, or tofu.",
  "You logged volume. You didn't log the brick.",
  "If this is a cut, protein is the lease. You missed rent.",
  "Snacks happened. Amino acids mostly didn't.",
  "You treated protein like a condiment. It isn't.",
  "Rebuild requires inventory. Your inventory is snacks and hope.",
  "The fire asked for grams. You answered with crunch.",
  "A high-kcal, low-protein day is how people stay soft and confused.",
  "You can hit calories and still miss the point. You found the point and missed it.",
  "Eggs, yogurt, fish, tofu, a scoop. Not a riddle.",
  "Your log has a plot hole shaped like chicken.",
  "Protein doesn't 'come later.' Later is how it never comes.",
  "You built a meal out of sides and called it dinner.",
  "The macros are a band. Protein is the drummer. You fired the drummer.",
  "If it's 'mostly plants,' cool. Plants still have to show up as protein.",
  "You don't get hypertrophy from folklore. You get it from the number.",
  "That protein bar in your bag doesn't count until it leaves the bag.",
  "You seasoned air and hoped for amino acids.",
  "Hit protein first next time. Then play with the fun food like an adult.",
  "The target is not a suggestion from a wellness blog. It's on your Self screen.",
  "You can love bread. Bread does not love your protein target back.",
  "This is how 'I lift but look the same' gets written. In grams.",
  "Add a food that had a mother or a well. Then we talk.",
  "You almost had a complete meal. Then you didn't.",
  "Protein is the boring chapter. Read it. The plot depends on it.",
];

export const late = [
  "Night calories count. They don't become 'tomorrow' because the lights are off.",
  "If it happened after 9, it still happened. Welcome to physics.",
  "The kitchen after dark is still the kitchen. Log the crime scene.",
  "Sleepy hunger is honest. Pretending it was a dream isn't.",
  "Midnight is not a legal jurisdiction with different kcal.",
  "You can have the snack. You cannot have the amnesia.",
  "Late isn't a personality. It's a timestamp. I can see it.",
  "The day doesn't end when you dim the lights. The log doesn't either.",
  "That wasn't a nightcap. That was a second dinner in a hoodie.",
  "Future-you will not thank you for the mystery kcal.",
  "If you're awake enough to chew, you're awake enough to tap Log.",
  "The fridge light is not a free pass. It's a spotlight.",
  "You don't get a discount for eating vertically in front of the fridge.",
  "Late snacks are allowed. Late fiction is not.",
  "The slot is called Snacks, not Secrets.",
  "You can close the kitchen. You already opened it. Own it.",
  "Hunger at 11 is still hunger. So is habit. Know which one you fed.",
  "I don't do 'it barely counts.' Barely is how totals happen.",
  "Put it in Fuel. Then go to bed like someone with a target.",
  "The fire doesn't sleep. Your alibi does.",
];

export const cutOver = [
  "You picked Cut and then catered a wedding. Pick again tomorrow.",
  "A cut with a surplus is just a bulk in denial.",
  "Lean is a direction. You walked the other way with snacks as a compass.",
  "The deficit is the whole joke. You skipped the punchline.",
  "You can't out-cardio a log that looks like a holiday.",
  "Cut means the target is smaller. You brought a parade anyway.",
  "If this is 'last hurrah,' the hurrah needs an end date. Today wasn't it.",
  "Fat loss doesn't care that the food was 'worth it.' The total does.",
  "You set the goal to get smaller and fed the day like a bulk. Confused fire.",
  "Honesty on a cut is boring portions. You chose plot twists.",
  "The scale will argue later. The log already testified.",
  "You can enjoy food on a cut. You cannot enjoy a second plot.",
  "Deficit math is rude. That's why it works. You tried to charm it.",
  "This is how cuts become 'I don't know what happened.' You do. It's here.",
  "Save the feast for a planned refeed. This was improvisation with extra cheese.",
];

export const bulkUnder = [
  "You picked Bulk and then ate like a rumor. Growth needs inventory.",
  "Muscle isn't summoned. It's fed. You sent thoughts and prayers.",
  "A bulk with a tiny log is a cut with better branding.",
  "You can't get bigger on vibes and a sad lunch.",
  "The surplus is the assignment. You turned in a draft.",
  "If you're afraid of getting soft, under-eating isn't the clever workaround.",
  "Growth is loud chewing plus iron. You whispered.",
  "You wanted the aesthetic of a bulk without the groceries.",
  "Hardgainer lore is usually 'I forgot to eat.' Congrats on the classic.",
  "The target is above TDEE on purpose. You hid under it.",
  "Lift heavier, sure. Also eat like the program isn't a joke.",
  "You can't bulk on coffee and character development.",
  "The fire expected a surplus. You brought a subplot about being 'not hungry.'",
  "If the scale isn't moving, check the log before the program.",
  "Bulk isn't an identity. It's a grocery list you actually used.",
];

export const recompMiss = [
  "Recomp is the narrow road. You wandered into a parking lot.",
  "Look like you train means train and eat like an adult. You picked one. Barely.",
  "Recomp doesn't forgive missing both the protein and the session.",
  "You wanted the middle path and took a nap in the ditch.",
  "Composition change is slow. Skipping the inputs makes it fictional.",
  "Recomp is not 'eat whatever, train whenever.' That's chaos with better lighting.",
  "The middle goal still has numbers. You treated them as décor.",
  "You can recomp. You cannot manifest it from a mixed log.",
  "Precision is the whole sport on recomp. You brought jazz.",
  "Hold the look means hit the boring targets. Today's log was modern art.",
];

export const hype = [
  "That's a clean hit. Heat up. Ego later.",
  "You did the boring thing on purpose. That's the whole sport.",
  "Ranked performance. No audience required.",
  "This is what 'I actually want it' looks like on a Tuesday.",
  "Fire noticed. Fire is a snob. You passed.",
  "Keep this energy and the roast department goes unemployed.",
  "You weren't lucky. You were accurate. That's rarer.",
  "On target, on protein, no speech. That's the flex.",
  "Quiet competence. My favorite genre.",
  "You fed the work and the work clocked in. Good.",
  "This is how Heat gets smug. Don't make it a personality.",
  "Boring log. Dangerous trajectory. I like it.",
  "You hit the number without turning it into content. Respect.",
  "That's adult behavior in an app with a mascot. Rare combo.",
  "The meter didn't have to shout. You already knew.",
  "Clean plate math. Clean session. Don't decorate it.",
  "You made today look easy because you didn't negotiate.",
  "This is the version of you the excuses are scared of.",
  "Heat's up because you were specific. Keep being specific.",
  "No parade. No collapse. Just the hit. That's professional.",
  "You treated the target like a job. Jobs get done.",
  "If this is your average, the rank list should be nervous.",
  "Protein present. Calories in the pocket. Iron not theoretical. Yes.",
  "You didn't 'crush it.' You completed it. Better.",
  "The fire will allow a small nod. Don't wink at the camera.",
  "Accuracy is hotter than intensity. You brought accuracy.",
  "This is how streaks get born: unremarkable honesty, repeated.",
  "You left fewer lies in the log. That's the whole product.",
  "Good. Now do it without announcing it to the group chat.",
  "The roast is on pause. Don't give it a reason to clock back in.",
  "You stacked the boring bricks. Buildings work that way.",
  "Hit. Logged. Trained. The trinity. Don't get mystical about it.",
  "You're allowed to feel proud for ten seconds. Then eat on time tomorrow.",
  "This is not a miracle. It's a completed checklist with a pulse.",
  "The numbers line up. That's prettier than a quote about grind.",
  "You made Heat's job easy. It almost said thank you. Almost.",
  "Keep the portions this honest and the jokes write themselves — in your favor.",
  "You showed up like the day was real. It is. Nice catch.",
  "That's a green day without the fake smile. I'll take it.",
  "Solid. Unfancy. Repeatable. That's the whole thesis.",
  "You didn't outsmart the target. You met it. Even better.",
  "The log looks like someone who read Self and obeyed. Novel.",
  "Heat likes this. I like this. Don't let noon ruin it.",
  "You put the work where the app can see it. That's the deal.",
  "A clean ratio is a love letter to future-you. Gross. Effective.",
  "You're playing the actual game, not the story about the game.",
  "This is maintenance of standards. Sexy in a spreadsheet way.",
  "You earned a quieter Ash. Don't miss the noise so much you sabotage.",
  "Good hit. Protect the evening like it owes you money.",
  "That's how people look like they train: they train, then they eat like it.",
];

export const compliments = [
  "Your log is cleaner than your inner monologue. Keep the log.",
  "You handled hunger like a professional, not a documentary.",
  "That session counted. So did the food. Matching set. Rare.",
  "You're getting better at being boring. That's a compliment.",
  "The honesty in Fuel is doing more than another program swap would.",
  "You picked the slot and meant it. Adults do that.",
  "Small, correct decisions. That's the whole glow-up, unfilmed.",
  "You didn't need a new identity. You needed this log. You did it.",
  "Heat's climbing because you stopped auditioning for chaos.",
  "You're allowed to be good at this without making it your personality.",
  "The plate and the iron agreed today. Treaty signed.",
  "You respected the target like it could fight back. It can. You won.",
  "That's composure. Not glamour. Composure lasts.",
  "You logged the unsexy food. That's how physiques happen in real life.",
  "I noticed the protein. Your muscles noticed first.",
  "You didn't flinch at the number. That's rarer than a PR.",
  "This is self-respect with a timestamp. Keep the timestamps.",
  "You made room for training without turning meals into a crisis.",
  "Good instincts today. Don't overfit them into a TED talk.",
  "You're becoming someone the evening can't easily kidnap. Good.",
  "The streak isn't luck. It's you, repeating an unremarkable yes.",
  "You chose the hit over the story. The story was going to be worse.",
  "That's a grown log. I'm almost polite. Don't get used to it.",
  "You stacked today like you intend to be here next month. Correct.",
  "Quiet wins. I'll allow it. Don't add a parade float.",
  "You're not 'on a journey.' You're on a target. And you landed.",
  "The boring breakfast did its job. Thank the oats privately.",
  "You treated Ash like a referee, not a therapist. Perfect.",
  "That's competence. Wear it. Don't livestream it.",
  "You made Heat look easy. It isn't. You just stopped lying.",
];

export const jokes = [
  "If calories were feelings, you'd still owe me a spreadsheet.",
  "I would say 'that's crazy' but the math is very sane. You're the plot.",
  "The fire doesn't do group chats. It does grams. Worse app, better outcomes.",
  "Your excuses have production value. The log has none. Fix the casting.",
  "I'm not mad. I'm arithmetic with a personality disorder.",
  "If this were a movie, the montage would skip the part you skipped.",
  "Congrats on opening the app. That's the tutorial. The boss is dinner.",
  "I can't debit shame. I can debit kcal. Guess which one I picked.",
  "Your potential called. It wants a protein source and a bedtime.",
  "This isn't tough love. It's regular love with a calculator.",
  "If I had a nickel for every 'I'll start Monday,' I could buy you chicken.",
  "The universe is not testing you. The fridge is. You keep losing.",
  "I believe in you the way I believe in gravity: non-negotiable, slightly rude.",
  "You want a catchphrase? Here's one: log it.",
  "I'm the ghost of protein future. The chains are whey. Move.",
  "If sarcasm burned kcal, you'd be shredded. It doesn't. Lift.",
  "This app is free. The jokes are free. The target is not optional.",
  "I'd clap but I don't have hands. Imagine a slow, judgmental clap.",
  "Your villain origin story is 'I was tired.' Everyone's tired. Next.",
  "Science is undefeated. Your narrative is on season 7 and slipping.",
  "I don't need your trauma dump. I need the grams. Then maybe a sentence.",
  "If willpower were Wi-Fi, you'd be in the hallway asking for the password. Eat.",
  "The fire's love language is consistency. Yours is 'one more episode.' Work on it.",
  "I'm not your mother. I'm worse. I remember the log.",
  "Consider this a Yelp review of your day. Two stars. Protein missing.",
  "You vs. the evening kitchen: historically, the kitchen wins. Upset it.",
  "I would suggest a walk. Not as poetry. As transportation for your blood.",
  "The good news is physics doesn't hold grudges. The bad news is it doesn't forget.",
  "If you're reading this instead of logging, that's the bit. Log.",
  "I'm basically a smoke alarm for your standards. Annoying. Correct.",
];

export const mixed = [
  "Not a disaster. Not a legend. Pick a lane before midnight.",
  "You're hovering. Hovering is how people stay average for years.",
  "The meter didn't clap. It also didn't spit. Do something decisive.",
  "Almost counts in horseshoes. This isn't horseshoes.",
  "You're in the hallway between trying and committing. Rent is due.",
  "Fine is a temperature. Fine is how years get stolen.",
  "There's a hit in here if you stop decorating it with snacks.",
  "You did some of the work. The fire does not grade on a curve.",
  "Meh is a choice. A long one. Career-length.",
  "You're collecting partial credit. Partial credit doesn't rank.",
  "The day's still editable. After midnight it becomes folklore.",
  "You showed up enough to be seen. Not enough to be feared.",
  "This is the log of someone who almost decided. Decide.",
  "Neither roast nor parade. That's your cue to pick one on purpose.",
  "You can still salvage this with a session or a real protein hit.",
  "Average is heavy if you wear it for a decade. Take it off.",
  "The numbers are shrugging. Shrugging is contagious. Don't catch it.",
  "You're not failing. You're stalling. Stalling is quieter and worse.",
  "A little more honesty in Fuel and this becomes a story I like.",
  "You left the day on medium. Medium is where momentum goes to nap.",
  "There's room above you. There's also a couch. Geography lesson.",
  "Close isn't closed. Hit the missing piece or own the miss.",
  "You're in range if you stop improvising the last third.",
  "The fire is waiting for a plot. You gave it B-roll.",
  "Could go either way. That's not exciting. That's unfinished homework.",
  "You did not bomb. You also did not audition for first place.",
  "This is recoverable before the kitchen lights come on. Move.",
  "A decisive snack or a decisive skip. Not a fog.",
  "You're one cooked protein away from a better paragraph.",
  "Don't wait for motivation to finish a day you already started.",
  "The log is a first draft. First drafts get protein and a walk.",
  "I need a cleaner ending. You still have hours. Use them.",
  "This isn't a verdict yet. Don't turn it into one by accident.",
  "You're allowed to be mid. You're not allowed to stay mid on purpose.",
  "Push one lever: food, iron, or bedtime. Push it.",
  "The day's a C+. C+ is how people explain five years later.",
  "Make a choice loud enough that Heat has to react.",
  "You can still be the protagonist. Right now you're extra #4.",
  "Tie the loose macros down. Then we can talk about pride.",
  "Not bad. Not done. Those are different sentences.",
];

export const lowHeat = [
  "Heat's in the basement. That's not a vibe. That's a receipt.",
  "You're allowed a comeback. Comebacks start with a logged meal, not a speech.",
  "The fire's small. Protect it like a match, not a firework show.",
  "Low Heat isn't identity. It's last week's homework. Do today's.",
  "You've been cooling. Cooling is reversible until you make it a lifestyle.",
  "Ash is in the name. It doesn't have to be in the forecast.",
  "Start tiny and honest. Grand rebrands are how people stall.",
  "The rank doesn't hate you. The log has been quiet. Wake it up.",
  "This is the part where people download a new app. Don't. Use this one.",
  "A bad week is data. A bad month with no logs is a disappearing act.",
  "You're not doomed. You're under-documented. Fix the second thing.",
  "Light the boring breakfast. Drama can wait.",
  "Heat will come back for labor, not for longing.",
  "Stop narrating the slump. Feed it chicken and a walk.",
  "The bottom is a great place to stop digging and start chewing.",
  "I don't need your lowest day to be cinematic. I need it to have protein.",
  "Comeback energy is oats, not a playlist. Play the oats.",
  "You've seen worse in other people. Be the person who logs anyway.",
  "Small Heat can still burn if you stop fanning it with excuses.",
  "Get one green input. Then another. That's the whole ladder.",
];

export const highHeat = [
  "You're hot. Don't get cute. Cute is how this reverses.",
  "Nuclear is a rental. Pay rent with the same boring hits.",
  "High Heat makes people sloppy. Stay pedantic.",
  "The fire likes you today. It likes honesty more. Keep paying.",
  "Don't spend this on a victory tour through the pantry.",
  "You're winning the quiet game. Quiet games die in loud kitchens.",
  "Protect the evening. That's where hot streaks go to audition for chaos.",
  "This is earned, not owed. Tomorrow will ask again.",
  "Stay mean about the details. Soft details melt Heat.",
  "You look like someone who might 'deserve' extra. You don't. The target does.",
  "Ride it. Don't spray champagne on the log.",
  "The snob fire is watching for the first cute decision. Don't audition.",
  "Keep your portions as arrogant as your Heat is high: precise.",
  "Success is a trigger for snacks in some people. Be the other people.",
  "You're allowed confidence. Confidence still logs the yogurt.",
  "Don't let the rank go to your head. Let it go to your calendar.",
  "Hot streak, cold kitchen after 9. That's the deal.",
  "The only flex left is repeating this without a TED talk.",
  "Stay humble in Fuel. The fire has a sense of humor and a memory.",
  "This is the dangerous part. You've already proven you can do it. Now prove you can not ruin it.",
];

export const streak = [
  "Streak on. Don't get folkloric. Just do the next log.",
  "Consecutive days is the whole magic trick. No rabbits. Just repeats.",
  "The streak is a chain. Chains break at the cute link. Don't be cute.",
  "You're stacking days like you mean the month, not the weekend.",
  "Streaks aren't personality. They're attendance. Keep attending.",
  "This is how identity changes: Tuesday, again.",
  "Don't celebrate the number so hard you skip the meal that protects it.",
  "The fire likes patterns. You're becoming one. Don't ghost the pattern.",
  "A streak is just honesty with a calendar. Keep the honesty.",
  "You're making 'showing up' look habitual. Good. Habits are supposed to look dull.",
  "Protect the streak from evening folklore and morning amnesia.",
  "If you're bored of being consistent, that's the sign it's working.",
  "The chain is heavier than a PR photo. Carry it.",
  "Streaks die when people feel 'safe.' You're not safe. You're in progress.",
  "Another day in a row. That's the plot. Don't add a twist.",
  "You're collecting proof, not vibes. Proof is the log.",
  "Keep the sequence. Sequences beat speeches.",
  "This many days in a row is a threat to your old excuses. Good.",
  "Don't let one social meal become the story of the streak. Log it and move.",
  "The streak doesn't love you. It loves the next honest input.",
];

export const heatCaptions = {
  nuclear: [
    "Nuclear. Don't get cute.",
    "Blinding. Ego stays outside.",
    "White-hot. Details, not victory laps.",
    "The snob fire is paying rent. Don't evict it with snacks.",
    "Peak heat. Pedantic portions. That's the deal.",
    "You're on fire. Fires still need fuel measured, not dumped.",
    "Legendary adjacent. Stay boring.",
    "This is the dangerous altitude. No cute landings.",
    "Heat this high is a job. Clock in again tomorrow.",
    "Don't flinch, don't feast. Hold.",
    "The meter is bragging. You shouldn't.",
    "Protect this like it can leave. It can.",
  ],
  hot: [
    "Hot. Protect this.",
    "Lit and load-bearing. Don't decorate it.",
    "Good heat. Evening is the test.",
    "You're cooking. Don't leave the kitchen unsupervised.",
    "Strong. Still mortal. Log like it.",
    "This is the good kind of warm. Keep the discipline loud.",
    "Heat's up. Standards stay mean.",
    "On. Stay on. That's the whole note.",
    "The fire is working. Don't give it folklore.",
    "Solid burn. No victory croissant.",
    "You're in the pocket. Pockets have holes. Watch 9pm.",
    "Hot enough to get sloppy. Don't.",
  ],
  lit: [
    "Lit. Not legendary.",
    "Warm with a job still to do.",
    "Respectable fire. Don't nap on it.",
    "You're in the game. Play the next possession.",
    "Good enough to build on. Not enough to coast.",
    "The coals are real. Feed them honestly.",
    "Mid-high. That's a platform, not a throne.",
    "Keep stacking. This band is where people get bored and ruin it.",
    "Alive. Make it obvious by midnight.",
    "Decent heat. Decent is a starting point.",
    "You're not cold. Don't get poetic. Get protein.",
    "Hold the line. The line is the target.",
  ],
  warm: [
    "Warm-ish. That's a warning.",
    "Tepid with potential. Potential expires.",
    "You can still choose a side today.",
    "Not cold. Not safe. Move.",
    "This is the shrug zone. Leave it.",
    "A little heat. A lot of undecided. Decide.",
    "Warning lights are still lights. Use them.",
    "You haven't lost the match. You're stalling in the lobby.",
    "Warm air. Need a real log to make it fire.",
    "Could go either way. That's a threat, not a vibe.",
    "Pick a lever. This temperature is a hallway.",
    "Almost a story. Finish a paragraph.",
  ],
  cool: [
    "Cooling. Shame incoming — or a comeback. Pick.",
    "Drafty. Close the window with a meal and a session.",
    "Heat's leaving. Chase it with honesty, not a new plan.",
    "This is how people 'take a break' for three months.",
    "Cold-adjacent. Light something real.",
    "The fire needs kindling. Kindling is lunch.",
    "You're drifting. Drifting is a direction. Steer.",
    "Not doomed. Documented poorly. Fix the log.",
    "Cooler than you think you are. That's the gift of meters.",
    "Come back small and exact. Grand gestures melt.",
    "This band is a fork: excuses or eggs.",
    "Start the comeback before the app becomes furniture.",
  ],
  ash: [
    "Ash. Start over like you mean it.",
    "Embers only. Breath on them: food, iron, bed.",
    "Bottom isn't identity. It's a timestamp. Move the timestamp.",
    "Rebuild with a breakfast that has a name.",
    "The fire went out from neglect, not destiny.",
    "One honest log is a match. Strike it.",
    "No montage. Oats. Then a walk. Then another log.",
    "You've been here. Leaving is a sequence, not a mood.",
    "Start ugly. Ugly logs light faster than perfect plans.",
    "The rank can wait. The plate cannot.",
    "Zero theater. One meal. That's the spell.",
    "Ash is a place. It is not a home. Walk.",
  ],
};

export const morningHot = [
  "You closed hot. Don't spend it on a victory croissant.",
  "Yesterday paid rent. Today is a new invoice.",
  "The streak is watching. Feed it something boring and correct.",
  "Good close. Now be suspiciously normal until bedtime.",
  "Heat carried overnight. You still have to earn daylight.",
  "You left a clean receipt. Don't forge tonight's.",
  "Yesterday's hit is not a coupon for chaos.",
  "Come in quiet. Repeat the hit. That's the elite move.",
  "The fire remembers. So will the pantry. Be the adult.",
  "Start like someone who already won once and got humble.",
];

export const morningCold = [
  "Yesterday left a bruise. Today is the apology. Make it edible and heavy.",
  "The close was ugly. Ugly is useful if you log breakfast on time.",
  "You don't owe a speech. You owe a plate and a pulse.",
  "Reset is a meal, not a personality reboot.",
  "The bruise is data. Eat, train, don't audition for a sequel.",
  "Comeback day. Not cinematic. Just protein and shoes.",
  "Yesterday slipped. Today can be pedantic. Pedantic wins.",
  "No hair shirt. Just a target. Hit nearer than last night.",
  "You already know what went wrong. Repeat less of it.",
  "Start before the story gets involved. Stories love a second collapse.",
];

export const morningBeige = [
  "Yesterday was beige. Beige is how years disappear. Pick a side before noon.",
  "Meh carries. Don't let it set the default.",
  "You closed lukewarm. Heat water or ice it. No more room temp.",
  "Beige days stack into a beige life. Add a session or a real hit.",
  "The middle is a trap with good lighting. Leave.",
  "Yesterday shrugged. Today should have an opinion.",
  "Lukewarm is reversible until dinner. Move.",
  "You didn't fail. You also didn't choose. Choose by lunch.",
  "Average overnight. That's your cue to be slightly mean with the details.",
  "Pick a lane while the coffee's still honest.",
];
